### ISSUE TITLE
快速开始-基础开发示例-注解-inArray无效

### ISSUE THREAD

**Issue by 2494911084** [easy-swoole/doc#191]
![image](https://user-images.githubusercontent.com/29133710/154876058-115901d6-e484-483e-9493-42ca0cf75685.png)
改为
![image](https://user-images.githubusercontent.com/29133710/154876119-83e0945a-ad07-486e-9062-cbfe9f108910.png)
生效。

测试代码：
![image](https://user-images.githubusercontent.com/29133710/154876196-2cb2b3d9-4ecb-4ada-9555-b6a935544ece.png)

**Comment by XueSiLf** [comment]
你好，本身就需要写成这种形式的：`inArray={0,1}`
